HOST    = x86_64-w64-mingw32
CFLAGS  = -std=c99 -Wall -Wextra -Os -Igl3w/ -Iglfw/include
LDFLAGS = -mwindows
LDLIBS  = -lwinmm -lopengl32
CC      = $(HOST)-gcc

demo.exe : demo.c gl3w/gl3w.c glfw/lib-mingw/libglfw3.a
	$(CC) $(CFLAGS) $(LDFLAGS) -o $@ $^ $(LDLIBS)

glfw/lib-mingw/libglfw3.a :
	wget 'https://github.com/glfw/glfw/releases/download/3.1.1/glfw-3.1.1.bin.WIN64.zip'
	unzip -q glfw-3.1.1.bin.WIN64.zip
	mv glfw-3.1.1.bin.WIN64 glfw

clean :
	$(RM) demo demo.exe
